id: PD8794FAF
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1GS58446
  instance_id: http://purl.bdrc.io/resource/IE1GS58446
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - མེ་རོ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1GS58445
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    95eb6b2869e14fd79cdbfd12b79a9a98:
      title: པོད ༡་མེ་རོ
      volume_number: 1
      base_file: UT1GS58446_I1GS58448_0000.txt
      reference: http://purl.bdrc.io/resource/VL9DBB105505E168F5
      image_group: I1GS58448
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1GS58446
  - http://purl.bdrc.io/resource/W1GS58446
  ocr_software: Namsel
created_at: '2021-12-22T10:27:20.786017'
last_modified_at: '2021-12-22T10:27:20.786023'
statistics:
  total_words: 21945
  total_non_words: 3828
quality:
  non_words_ratio: 0.17
